<a href="https://colab.research.google.com/github/sandeep838116/Pandas/blob/main/Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pandas

Pandas is an open-source Python library used for data manipulation, analysis and cleaning. It provides fast and flexible tools to work with tabular data, similar to spreadsheets or SQL tables.

### Key Advantages of Using Pandas

* **Efficient Data Cleaning:** Easily find, remove, or fill missing values (`NaN`) and drop duplicate rows.
* **Fast Data Manipulation:** Sort, filter, group (`GroupBy`), merge, join, and reshape datasets quickly without writing slow loops.
* **Handles Multiple File Formats:** Read and write data seamlessly from and to CSV, Excel, JSON, and SQL databases.
* **Less Code, More Productivity:** Perform complex mathematical operations and data transformations in a single line of code.
* **Ecosystem Integration:** Works smoothly with NumPy for calculations, Matplotlib/Seaborn for visualization, and scikit-learn for machine learning.
* **Labeled Indexing:** Automatically aligns data using row and column labels, preventing mix-ups during calculations.

The primary reason to use Pandas over NumPy is that Pandas is designed specifically for data manipulation, cleaning, and tabular data analysis, whereas NumPy is built for low-level numerical computing and matrix operations. While Pandas is actually built on top of NumPy, it provides high-level data structures (like DataFrames) that make working with real-world, messy datasets significantly easier.

# Pandas vs NumPy: Key Advantages Comparison

| Feature | NumPy | Pandas Advantage |
| :--- | :--- | :--- |
| **Data Alignment & Labels** | Relies strictly on numerical indexing (`0, 1, 2...`). | **Labeled rows and columns** (like an Excel sheet or SQL table), making code intuitive and readable. |
| **Data Types (Heterogeneity)** | Optimized strictly for homogeneous data (all elements must be the same type, usually numbers). | Handles **mixed data types** (strings, dates, integers, and floats) seamlessly within a single DataFrame. |
| **Missing Data Handling** | Limited built-in support for missing data. | Built-in functions to **easily detect, fill, or drop missing values** (`NaN` data). |
| **Data Merging & Joining** | Requires manual array stacking or concatenation. | Powerful **SQL-like merging, joining, and concatenation** out of the box. |
| **Grouping & Aggregations** | Does not natively support grouping operations. | Includes a robust **`groupby()` feature** to easily split, apply, and aggregate data. |
| **Time-Series Support** | Basic date routing capabilities. | **Elite time-series features**, including easy date parsing, frequency resampling, and window statistics. |
| **Data I/O Tools** | Difficult to parse complex file formats. | Easily reads and writes to **CSVs, Excel files, SQL databases, and JSON** with single-line commands. |

## Importing Pandas

In [2]:
import pandas as pd
import numpy as np

## Creating a pandas Series

A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) of the same type and an associated array of data labels, called its index.

Key Features of Pandas Series:

- Supports integer-based and label-based indexing.
- Stores heterogeneous data types.
- Offers a variety of built-in methods for data manipulation and analysis.

In [3]:
#Creating a Series from a NumPy Array
data = np.array(['g', 'e', 'e', 'k', 's'])

ser = pd.Series(data)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: object

In [4]:
# Creating a Series from a List
data_list = ['g', 'e', 'e', 'k', 's']

ser = pd.Series(data_list)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: object

In [5]:
# Creating a Series from a Dictionary
data_dict = {'Sandy': 10, 'sandeep': 20, 'sujeet': 30}

ser = pd.Series(data_dict)
print(ser)

Sandy      10
sandeep    20
sujeet     30
dtype: int64

In [6]:
# Creating a Series Using NumPy Functions
ser = pd.Series(np.linspace(1, 10, 5))
print(ser)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [7]:
# Creating a Series Using range()
ser = pd.Series(range(5, 15))
print(ser)

0     5
1     6
2     7
3     8
4     9
5    10
6    11
7    12
8    13
9    14
dtype: int64

The string representation of a Series displayed interactively shows the index on the left and the values on the right. Since we did not specify an index for the data, a default one consisting of the integers 0 through N - 1 (where N is the length of the data) is created.

In [9]:
# Creating a pandas series with explict indexing.
ser = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
ser

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
# Creating a Series Using List Comprehension
ser=pd.Series(range(1,20,3), index=[x for x in 'abcdefg'])
print(ser)

a     1
b     4
c     7
d    10
e    13
f    16
g    19
dtype: int64

### Accessing elements of Series
In Pandas we can access element of series using two ways:

- Position-based Indexing - In this we use numerical positions similar to lists in Python.
- Label-based Indexing - This method also custom index labels assigned to elements.

**1. Position-based Indexing**

In order to access the series element refers to the index number. Use the index operator []to access an element in a series. The index must be an integer. In order to access multiple elements from a series we use Slice operation.

In [10]:
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data)

print(ser[:5])

0    g
1    e
2    e
3    k
4    s
dtype: object

**2. Label-based Indexing**

In order to access an element from series, we have to set values by index label. A Series is like a fixed-size dictionary in that we can get and set values by index label. let's see a example to understand this

In [13]:
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data,index=[10,11,12,13,14,15,16,17,18,19,20,21,22])

print(ser[16])

o

### Indexing and Selecting Data in Series
Indexing in pandas means simply selecting particular data from a Series. Indexing could mean selecting all the data some of the data from particular columns. Indexing can also be known as Subset Selection. We can use .iloc[] for position-based selection and .loc[] for label-based selection.

#### .loc[]

In pandas, df.loc[] is a property used to select and modify data in a DataFrame or Series using **labels** (row and column names) or boolean conditions.

- Inclusive Slicing: When you slice with text labels (e.g., 'A':'C'), both the start and the stop bounds are included.
- Integer Labels: If your row index contains literal integers (like 0, 1, 2), .loc[0] will look for the label 0, not the first position in the table.

**1. Indexing a Series using .loc[]**

In [16]:
population = pd.Series(
    [8.3, 3.8, 2.6, 1.4],
    index=['New York', 'Los Angeles', 'Chicago', 'San Diego']
)
la_pop = population.loc['Los Angeles']
la_pop

np.float64(3.8)

**2. Slicing Labels**

Extract a range of elements. Remember, pandas label slicing includes the stop endpoint.

In [18]:
subset = population.loc['New York':'Chicago']
subset

New York       8.3
Los Angeles    3.8
Chicago        2.6
dtype: float64

**3. Filtering with Boolean Conditions**

Pass a conditional statement to filter the index values.

In [20]:
large_cities = population.loc[population > 3.0]
large_cities

New York       8.3
Los Angeles    3.8
dtype: float64

**4. Updating Values In-Place**

Modify existing elements or add a completely new label directly.

In [21]:
# Update Chicago's population
population.loc['Chicago'] = 2.7

# Add a completely new city and its value to the Series
population.loc['Houston'] = 2.3

#### .iloc[]

In a pandas Series, series.iloc[] is used to select, filter, or modify data based strictly on its integer **position** (0-indexed location), completely ignoring any custom index labels the Series might have [1].

In [22]:
prices = pd.Series(
    [1.99, 5.49, 12.00, 0.99],
    index=['Apple', 'Bread', 'Cheese', 'Donut']
)

**1. Indexing**

In [23]:
# Returns: 1.99 (position 0)
first_item = prices.iloc[0]

# Negative indexing works too! Returns: 0.99 (the last item)
last_item = prices.iloc[-1]

**2. Slicing Positions**

Extract a range of elements. Unlike .loc, .iloc slicing follows standard Python rules: the start index is inclusive, but the stop index is exclusive [1].

In [25]:
subset = prices.iloc[0:2]
subset

Apple    1.99
Bread    5.49
dtype: float64

**3. Selecting a List of Specific Positions**

Pass a list of integers to pull non-consecutive elements [1].

In [26]:
picked_items = prices.iloc[[0, 3]]
picked_items

Apple    1.99
Donut    0.99
dtype: float64

**4. Updating Values In-Place**

Modify an existing element directly using its current numerical position [1].

In [27]:
prices.iloc[1] = 5.99

**Why is .iloc crucial for Series? (The Index Trap)**

The true power of .iloc becomes obvious when your Series has an integer index that is out of order or missing steps (e.g., after filtering or sorting) [1].

In [28]:
# A Series where labels are integers, but shuffled
s = pd.Series(['a', 'b', 'c'], index=[2, 0, 1])

# s.loc[0]  -> Returns 'b' (looks for the literal LABEL 0)
# s.iloc[0] -> Returns 'a' (looks for the absolute FIRST POSITION)

Using .iloc guarantees you are fetching data based on where it sits in the Series, not what it is named [1].

### Binary Operations on Pandas Series

Pandas allows performing binary operations on Series, such as addition, subtraction, multiplication and division. These operations can be performed using functions like .add() , .sub(), .mul() and .div().


| Method | Description |
| :--- | :--- |
| `sub()` | Subtracts a series or list-like object from the caller series. |
| `mul()` | Multiplies the caller series by a series or list-like object. |
| `div()` | Divides the caller series by a series or list-like object. |
| `sum()` | Returns the sum of the values for the requested axis. |
| `prod()` | Returns the product of the values for the requested axis. |
| `mean()` | Returns the mean of the values for the requested axis. |
| `pow()` | Raises the caller series elements to the exponential power of the passed series. |
| `abs()` | Returns the absolute numeric value of each element in the Series/DataFrame. |
| `cov()` | Computes the covariance between two series. |

In [31]:
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([2, 5, 3])

# Examples of the operations:
print("Subtraction:\n", s1.sub(s2))
print("\nMultiplication:\n", s1.mul(s2))
print("\nDivision:\n", s1.div(s2))
print("\nPower (s1 raised to s2):\n", s1.pow(s2))
print("\nCovariance:\n", s1.cov(s2))

# Statistical summaries (caller only)
print("\nSum of s1:", s1.sum())
print("Mean of s1:", s1.mean())

Subtraction:
 0     8
1    15
2    27
dtype: int64

Multiplication:
 0     20
1    100
2     90
dtype: int64

Division:
 0     5.0
1     4.0
2    10.0
dtype: float64

Power (s1 raised to s2):
 0        100
1    3200000
2      27000
dtype: int64

Covariance:
 5.0

Sum of s1: 60
Mean of s1: 20.0

### Conversion Operation on Series

Conversion operations allow transforming data types within a Series. This can be useful for ensuring consistency in data types. In order to perform conversion operation we have various function which help in conversion like .astype(), .tolist(), etc.


| Method | Description |
| :--- | :--- |
| `astype()` | Casts the Series to a specified data type (e.g., `int`, `float`, `str`, `category`). |
| `tolist()` / `to_list()` | Converts the Series elements into a standard native Python list. |
| `to_numpy()` | Converts the Series into a NumPy `ndarray`. |
| `to_frame()` | Converts the one-dimensional Series into a two-dimensional pandas DataFrame. |
| `to_dict()` | Converts the Series into a Python dictionary, mapping index labels to values. |
| `to_json()` | Converts the Series data into a JSON string representation. |
| `convert_dtypes()` | Automatically converts columns to the best possible data types that support `pd.NA`. |
| `infer_objects()` | Attempts to infer better, more specific data types for Series containing `object` types. |

In [32]:
s = pd.Series([10, 20, 30], index=['Item_A', 'Item_B', 'Item_C'])
print("Original Series:\n", s, f"\nType: {s.dtype}\n")

# 1. Convert data type using astype()
s_float = s.astype(float)
print("1. astype(float):\n", s_float, "\n")

# 2. Convert to native Python List
py_list = s.tolist()
print("2. tolist():", py_list, f"| Type: {type(py_list)}")

# 3. Convert to NumPy Array
np_array = s.to_numpy()
print("3. to_numpy():", np_array, f"| Type: {type(np_array)}")

# 4. Convert to DataFrame
df_version = s.to_frame(name='Values')
print("4. to_frame():\n", df_version, "\n")

# 5. Convert to Python Dictionary
py_dict = s.to_dict()
print("5. to_dict():", py_dict, f"| Type: {type(py_dict)}")

Original Series:
 Item_A    10
Item_B    20
Item_C    30
dtype: int64
Type: int64

1. astype(float):
 Item_A    10.0
Item_B    20.0
Item_C    30.0
dtype: float64

2. tolist(): [10, 20, 30] | Type: <class 'list'>
3. to_numpy(): [10 20 30] | Type: <class 'numpy.ndarray'>
4. to_frame():
         Values
Item_A      10
Item_B      20
Item_C      30

5. to_dict(): {'Item_A': 10, 'Item_B': 20, 'Item_C': 30} | Type: <class 'dict'>

## Creating Pandas DataFrame

A DataFrame represents a rectangular table of data and contains an ordered, named collection of columns, each of which can be a different value type (numeric, string, Boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dictionary of Series all sharing the same index.

**While a DataFrame is physically two-dimensional, you can use it to represent higher dimensional data in a tabular format using hierarchical indexing.**

In [33]:
# Creating an Empty DataFrame
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [34]:
# Creating a DataFrame from a List
fruits = ['Apple', 'Banana', 'Cherry', 'Date']
df = pd.DataFrame(fruits, columns=['Fruit_Name'])

print(df)

  Fruit_Name
0      Apple
1     Banana
2     Cherry
3       Date

In [ ]:
# Creating a DataFrame from a dictionary
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [35]:
# Creating DataFrame from dict of Numpy Array
data = { 'A': np.array([1, 4, 7]),
         'B': np.array([2, 5, 8]),
         'C': np.array([3, 6, 9]) }
df = pd.DataFrame(data)
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [36]:
# Creating a DataFrame from a List of Dictionaries
data = [
    {'name': 'Mike', 'degree': 'MBA', 'score': 90},
    {'name': 'Dan', 'degree': 'BCA', 'score': 40},
    {'name': 'Emilia', 'degree': 'M.Tech', 'score': 80},
]
df = pd.DataFrame(data)
print(df)

     name  degree  score
0    Mike     MBA     90
1     Dan     BCA     40
2  Emilia  M.Tech     80

In [38]:
# Create pandas dataframe from lists using zip
Name = ['tom', 'krish', 'nick', 'juli']
Age = [25, 30, 26, 22]

# get the list of tuples from two lists.
# and merge them by using zip().
list_of_tuples = list(zip(Name, Age))

# Converting lists of tuples into
# pandas Dataframe.
df = pd.DataFrame(list_of_tuples, columns = ['Name', 'Age'])

df

    Name  Age
0    tom   25
1  krish   30
2   nick   26
3   juli   22

### Indexing in DataFrame

In [40]:
data = {
    'Product': ['Laptop', 'Smartphone', 'Tablet', 'Monitor', 'Keyboard'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Accessories', 'Accessories'],
    'Price':[100000,20000,25000,19000,1000],
    'Stock': [15, 0, 24, 8, 50]
}
row_labels = ['P001', 'P002', 'P003', 'P004', 'P005']
df = pd.DataFrame(data, index=row_labels)

print("--- ORIGINAL DATAFRAME ---")
print(df)

--- ORIGINAL DATAFRAME ---
         Product     Category   Price  Stock
P001      Laptop  Electronics  100000     15
P002  Smartphone  Electronics   20000      0
P003      Tablet  Electronics   25000     24
P004     Monitor  Accessories   19000      8
P005    Keyboard  Accessories    1000     50

#### .loc[]

- .loc[] is INCLUSIVE on both ends. df.loc['A':'C'] returns rows A, B, and C.

In [41]:
# Select a single cell value
smartphone_price = df.loc['P002', 'Price']
print(f"A. Single Value Lookup -> Smartphone Price: ${smartphone_price}")

# Slicing rows and columns (Endpoints are INCLUSIVE!)
loc_slice = df.loc['P002':'P004', 'Product':'Price']
print("\nB. Label Slice (P002 to P004, Product to Price):")
print(loc_slice)

# Boolean Filtering (Conditional selection)
in_stock_df = df.loc[df['Stock'] > 10, ['Product', 'Stock']]
print("\nC. Boolean Filter (Stock > 10):")
print(in_stock_df)

# In-place modification using labels
df.loc['P005', 'Price'] = 75
print(f"\nD. Updated Keyboard Price: ${df.loc['P005', 'Price']}")

A. Single Value Lookup -> Smartphone Price: $20000

B. Label Slice (P002 to P004, Product to Price):
         Product     Category  Price
P002  Smartphone  Electronics  20000
P003      Tablet  Electronics  25000
P004     Monitor  Accessories  19000

C. Boolean Filter (Stock > 10):
       Product  Stock
P001    Laptop     15
P003    Tablet     24
P005  Keyboard     50

D. Updated Keyboard Price: $75

#### .iloc[]

- .iloc[] is EXCLUSIVE on the upper bound, exactly like standard Python lists. df.iloc[0:2] returns rows 0 and 1. Row 2 is excluded.

In [42]:
# Select a single cell value by position
laptop_price = df.iloc[0, 2]
print(f"A. Position Lookup -> Row 0, Col 2 Value: {laptop_price}")

# Example B: Slicing rows and columns (Stop bound is EXCLUSIVE!)
iloc_slice = df.iloc[1:3, 0:2]
print("\nB. Position Slice (Rows 1:3, Cols 0:2):")
print(iloc_slice)

# Selecting specific isolated indices using lists
isolated_select = df.iloc[[0, 4], [0, 3]]
print("\nC. List of Specific Row/Col Positions ([0,4], [0,3]):")
print(isolated_select)

# Negative index positioning
last_item_stock = df.iloc[-1, -1]
print(f"\nD. Negative Indexing -> Stock of last item: {last_item_stock}")

A. Position Lookup -> Row 0, Col 2 Value: 100000

B. Position Slice (Rows 1:3, Cols 0:2):
         Product     Category
P002  Smartphone  Electronics
P003      Tablet  Electronics

C. List of Specific Row/Col Positions ([0,4], [0,3]):
       Product  Stock
P001    Laptop     15
P005  Keyboard     50

D. Negative Indexing -> Stock of last item: 50

**The Integer Index Pitfall**

If your DataFrame index contains actual integers (e.g., [10, 20, 30]), .loc and .iloc behave very differently:
- df.loc[10] looks for the row explicitly named 10.
- df.iloc[0] looks for the row sitting at the absolute first position, regardless of its numerical name.
- **Rule of thumb:** Avoid using simple assignment operations like df[0] when working with mixed numerical indices; explicitly use .loc or .iloc to avoid unexpected bugs.

**Dynamic Filtering with Lambdas**

Both .loc and .iloc accept callable lambda functions. This is incredibly helpful when cleaning data pipelines where the DataFrame name changes or is anonymous:

In [43]:
df.loc[lambda x: x['Price'] > x['Price'].mean()]

     Product     Category   Price  Stock
P001  Laptop  Electronics  100000     15

## Index Objects

pandas’s Index objects are responsible for holding the axis labels (including a DataFrame's column names) and other metadata (like the axis name or names). Any array or other sequence of labels you use when constructing a Series or DataFrame is internally converted to an Index.

In [44]:
# Creating a Series with a custom index
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

# Extracting the Index object
index = obj.index
print("Index:", index)

# Slicing an Index object
print("Sliced Index:", index[1:])

Index: Index(['a', 'b', 'c'], dtype='object')
Sliced Index: Index(['b', 'c'], dtype='object')

**Immutability**

Index objects are immutable and thus cannot be modified directly by the user. Trying to change an index element will raise a *TypeError*.

In [45]:
# This will raise a TypeError: Index does not support mutable operations
try:
    index[1] = "d"
except TypeError as e:
    print(f"Error: {e}")

Error: Index does not support mutable operations

Immutability makes it completely safe to share Index objects across multiple data structures without worrying about unintended side effects:

In [46]:
# Creating an Index object directly
labels = pd.Index(np.arange(3))
print("Labels:", labels)

# Reusing the exact same index object for a new Series
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

# Verifying if they point to the exact same reference in memory
print("Is shared reference?", obj2.index is labels)

Labels: Index([0, 1, 2], dtype='int64')
Is shared reference? True

**Set-Like Behaviour**

In addition to being array-like, an Index also behaves like a fixed-size set, letting you run membership tests (using the in keyword)

In [47]:
# Creating a sample DataFrame with custom row and column indices
data = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(data)
frame3.columns.name = "state"
frame3.index.name = "year"

print("--- DataFrame ---")
print(frame3)

# Checking membership in columns
print("\nIs 'Ohio' in columns?", "Ohio" in frame3.columns)

# Checking membership in rows
print("Is 2003 in row index?", 2003 in frame3.index)

--- DataFrame ---
state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

Is 'Ohio' in columns? True
Is 2003 in row index? False

**Duplicate Labels**

Unlike standard Python sets, a pandas Index can contain duplicate labels.

In [48]:
dup_index = pd.Index(["foo", "foo", "bar", "bar"])
print("Index with duplicates:", dup_index)

Index with duplicates: Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

**Note:** Selections with duplicate labels using methods like .loc[] will select all occurrences of that label simultaneously.

### Pandas Index Methods & Properties Reference

| Method / Property | Description |
| :--- | :--- |
| **`append()`** | Concatenate with additional Index objects, producing a new Index. |
| **`difference()`** | Compute set difference as an Index. |
| **`intersection()`** | Compute set intersection. |
| **`union()`** | Compute set union. |
| **`isin()`** | Compute Boolean array indicating whether each value is contained in the passed collection. |
| **`delete()`** | Compute new Index with element at Index `i` deleted. |
| **`drop()`** | Compute new Index by deleting passed values. |
| **`insert()`** | Compute new Index by inserting element at Index `i`. |
| **`is_monotonic`** | Returns `True` if each element is greater than or equal to the previous element. |
| **`is_unique`** | Returns `True` if the Index has no duplicate values. |
| **`unique()`** | Compute the array of unique values in the Index. |