<a href="https://colab.research.google.com/github/sandeep838116/Pandas/blob/main/Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Viewing data in pandas

### Pandas Dataframe/Series.head() method - Python

The head() method structure and contents of our dataset without printing everything. By default it returns the first five rows but this can be customized to return any number of rows. It is commonly used to verify that data has been loaded correctly, check column names and inspect the initial records.

In [38]:
import pandas as pd
import numpy as np

data = pd.read_csv("/content/nba.csv")

print("NBA Dataset (First 5 Rows):")
print(data.head())

NBA Dataset (First 5 Rows):
            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

**Syntax:**

 - DataFrame.head(n=5)

 - Series.head(n=5)

**Parameter:**

- n: Number of rows to retrieve from the top of the DataFrame or Series.

**Return:** It returns the first n rows of the DataFrame or Series as a new DataFrame or Series.

In [2]:
series = data["Name"]

top = series.head(n = 7)

print("NBA Dataset (First 7 Rows):")
print(top)

NBA Dataset (First 7 Rows):
0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
Name: Name, dtype: object

In [3]:
# Describing Specific Columns with head()
salary_name = data[['Name', 'Salary']].head()

print("First 5 Rows of Name and Salary Columns:")
print(salary_name)

First 5 Rows of Name and Salary Columns:
            Name     Salary
0  Avery Bradley  7730337.0
1    Jae Crowder  6796117.0
2   John Holland        NaN
3    R.J. Hunter  1148640.0
4  Jonas Jerebko  5000000.0

In [4]:
# Using head() After Sorting a DataFrame
sorted_data = data.sort_values(by='Age', ascending=True)

top_sorted = sorted_data.head()

print("First 5 Rows After Sorting by Age:")
print(top_sorted)

First 5 Rows After Sorting by Age:
                   Name                    Team  Number Position   Age Height  \
226       Rashad Vaughn         Milwaukee Bucks    20.0       SG  19.0    6-6
122        Devin Booker            Phoenix Suns     1.0       SG  19.0    6-6
452          Trey Lyles               Utah Jazz    41.0       PF  20.0   6-10
427     Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8
410  Karl-Anthony Towns  Minnesota Timberwolves    32.0        C  20.0    7-0

     Weight   College     Salary
226   202.0      UNLV  1733040.0
122   206.0  Kentucky  2127840.0
452   234.0  Kentucky  2239800.0
427   240.0    Kansas   525093.0
410   244.0  Kentucky  5703600.0

### Pandas Dataframe/Series.tail() method - Python
The tail() method allows us to quickly preview the last few rows of a DataFrame or Series. This method is useful for data exploration as it helps us to inspect the bottom of the dataset without printing everything. It is commonly used to verify that data has been loaded correctly, check the last records and inspect the data towards the end of a dataset.

In [5]:
print("NBA Dataset (Last 5 Rows):")
print(data.tail())

NBA Dataset (Last 5 Rows):
             Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN

        Salary
453  2433333.0
454   900000.0
455  2900000.0
456   947276.0
457        NaN

**Syntax:**

- DataFrame.tail(n=5)

- Series.tail(n=5)

**Parameter:**

- n: Number of rows to retrieve from the bottom of the DataFrame or Series.

**Return:** It returns the last n rows of the DataFrame or Series as a new DataFrame or Series.

In [6]:
series = data["Name"]

bottom = series.tail(n = 7)

print("NBA Dataset (Last 7 Rows):")
print(bottom)

NBA Dataset (Last 7 Rows):
451    Chris Johnson
452       Trey Lyles
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, dtype: object

In [7]:
# Using tail() on a Series
salary = data['Salary']

print("Last 5 Salaries:")
print(salary.tail())

Last 5 Salaries:
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, dtype: float64

In [8]:
# Describing Specific Columns with tail()
salary_name = data[['Name', 'Salary']].tail()

print("Last 5 Rows of Name and Salary Columns:")
print(salary_name)

Last 5 Rows of Name and Salary Columns:
             Name     Salary
453  Shelvin Mack  2433333.0
454     Raul Neto   900000.0
455  Tibor Pleiss  2900000.0
456   Jeff Withey   947276.0
457           NaN        NaN

In [9]:
# Using tail() After Sorting a DataFrame
sorted_data = data.sort_values(by='Age', ascending=False)

bottom_sorted = sorted_data.tail()

print("Last 5 Rows After Sorting by Age:")
print(bottom_sorted)

Last 5 Rows After Sorting by Age:
                   Name                    Team  Number Position   Age Height  \
452          Trey Lyles               Utah Jazz    41.0       PF  20.0   6-10
410  Karl-Anthony Towns  Minnesota Timberwolves    32.0        C  20.0    7-0
226       Rashad Vaughn         Milwaukee Bucks    20.0       SG  19.0    6-6
122        Devin Booker            Phoenix Suns     1.0       SG  19.0    6-6
457                 NaN                     NaN     NaN      NaN   NaN    NaN

     Weight   College     Salary
452   234.0  Kentucky  2239800.0
410   244.0  Kentucky  5703600.0
226   202.0      UNLV  1733040.0
122   206.0  Kentucky  2127840.0
457     NaN       NaN        NaN

### Pandas DataFrame describe() Method
The describe() method in Pandas generates descriptive statistics of DataFrame columns which provides key metrics like mean, standard deviation, percentiles and more. It works with numeric data by default but can also handle categorical data which offers insights like the most frequent value and the number of unique entries. In this article, we'll see how to use describe() for both numeric and categorical data.

**Syntax:**
- DataFrame.describe(percentiles=None, include=None, exclude=None)

**Parameters:**

- percentiles: A list of numbers between 0 and 1 specifying which percentiles to return. The default is None which returns the 25th, 50th and 75th percentiles.
- include: A list of data types to include in the summary like int, float, object for strings. Default is None means all numeric types are included.
- exclude: A list of data types to exclude from the summary. Default is None means no types are excluded.

In [10]:
print("Summary Table Generated by .describe() Method:")
print(data.describe())

Summary Table Generated by .describe() Method:
           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

**Descriptive Statistics for Numerical Columns generated using .describe() Method**

- count: Total number of non-null entries in each column.
- mean: Average (mean) of the values in the column.
- std: Standard deviation showing how spread out the values are.
- min: Minimum value in the column.
- 25%: The 25th percentile (Q1) which means 25% of the data points are less than this value.
- 50%: Median value (50th percentile) where half the data points are below it.
- 75%: The 75th percentile (Q3) means 75% of the data points are below this value.
- max: Maximum value in the column.

In [11]:
# Customizing describe() with Percentiles
percentiles = [.20, .40, .60, .80]
include = ['object', 'float', 'int']

desc = data.describe(percentiles=percentiles, include=include)

print(desc)

               Name                  Team      Number Position         Age  \
count           457                   457  457.000000      457  457.000000
unique          457                    30         NaN        5         NaN
top     Jeff Withey  New Orleans Pelicans         NaN       SG         NaN
freq              1                    19         NaN      102         NaN
mean            NaN                   NaN   17.678337      NaN   26.938731
std             NaN                   NaN   15.966090      NaN    4.404016
min             NaN                   NaN    0.000000      NaN   19.000000
20%             NaN                   NaN    4.000000      NaN   23.000000
40%             NaN                   NaN   10.000000      NaN   25.000000
50%             NaN                   NaN   13.000000      NaN   26.000000
60%             NaN                   NaN   18.600000      NaN   27.000000
80%             NaN                   NaN   30.000000      NaN   30.000000
max             NaN                   NaN   99.000000      NaN   40.000000

       Height      Weight   College        Salary
count     457  457.000000       373  4.460000e+02
unique     18         NaN       118           NaN
top       6-9         NaN  Kentucky           NaN
freq       59         NaN        22           NaN
mean      NaN  221.522976       NaN  4.842684e+06
std       NaN   26.368343       NaN  5.229238e+06
min       NaN  161.000000       NaN  3.088800e+04
20%       NaN  195.600000       NaN  9.472760e+05
40%       NaN  213.400000       NaN  1.938840e+06
50%       NaN  220.000000       NaN  2.839073e+06
60%       NaN  230.000000       NaN  3.815000e+06
80%       NaN  245.000000       NaN  8.042895e+06
max       NaN  307.000000       NaN  2.500000e+07

In [12]:
# Describing String (Object) Data
desc = data["Name"].describe()

print(desc)

count             457
unique            457
top       Jeff Withey
freq                1
Name: Name, dtype: object

**For string (object) data, describe() provides:**

- count: Total number of non-null values.
- unique: Number of unique values in the column.
- top: Most frequent value in the column.
- freq: Frequency of the most common value.

In [13]:
# Describing Specific Columns with describe()
salary_desc = data["Salary"].describe()

print(salary_desc)

count    4.460000e+02
mean     4.842684e+06
std      5.229238e+06
min      3.088800e+04
25%      1.044792e+06
50%      2.839073e+06
75%      6.500000e+06
max      2.500000e+07
Name: Salary, dtype: float64

In [14]:
# Describing Data with include='all'
# By using the include='all' parameter we can generate a summary for all columns in the DataFrame regardless of data type.
# This is helpful when we want to analyze both numeric and categorical data at the same time.

desc_all = data.describe(include='all')

print(desc_all)

               Name                  Team      Number Position         Age  \
count           457                   457  457.000000      457  457.000000
unique          457                    30         NaN        5         NaN
top     Jeff Withey  New Orleans Pelicans         NaN       SG         NaN
freq              1                    19         NaN      102         NaN
mean            NaN                   NaN   17.678337      NaN   26.938731
std             NaN                   NaN   15.966090      NaN    4.404016
min             NaN                   NaN    0.000000      NaN   19.000000
25%             NaN                   NaN    5.000000      NaN   24.000000
50%             NaN                   NaN   13.000000      NaN   26.000000
75%             NaN                   NaN   25.000000      NaN   30.000000
max             NaN                   NaN   99.000000      NaN   40.000000

       Height      Weight   College        Salary
count     457  457.000000       373  4.460000e+02
unique     18         NaN       118           NaN
top       6-9         NaN  Kentucky           NaN
freq       59         NaN        22           NaN
mean      NaN  221.522976       NaN  4.842684e+06
std       NaN   26.368343       NaN  5.229238e+06
min       NaN  161.000000       NaN  3.088800e+04
25%       NaN  200.000000       NaN  1.044792e+06
50%       NaN  220.000000       NaN  2.839073e+06
75%       NaN  240.000000       NaN  6.500000e+06
max       NaN  307.000000       NaN  2.500000e+07

# Selection and slicing

| Indexing Option | DataFrame Type Notes |
| :--- | :--- |
| `df[column]` | Select single column or sequence of columns from the DataFrame; special case conveniences: Boolean array (filter rows), slice (slice rows), or Boolean DataFrame (set values based on some criterion) |
| `df.loc[rows]` | Select single row or subset of rows from the DataFrame by label |
| `df.loc[:, cols]` | Select single column or subset of columns by label |
| `df.loc[rows, cols]` | Select both row(s) and column(s) by label |
| `df.iloc[rows]` | Select single row or subset of rows from the DataFrame by integer position |
| `df.iloc[:, cols]` | Select single column or subset of columns by integer position |
| `df.iloc[rows, cols]` | Select both row(s) and column(s) by integer position |
| `df.at[row, col]` | Select a single scalar value by row and column label |
| `df.iat[row, col]` | Select a single scalar value by row and column position (integers) |
| `reindex` method | Select either rows or columns by labels |

## Dealing with Rows and Columns in Pandas DataFrame

#### Dealing with Columns

In [16]:
# Selecting Columns
df = pd.read_csv('nba.csv')

print(data[['Name', 'Age']])

              Name   Age
0    Avery Bradley  25.0
1      Jae Crowder  25.0
2     John Holland  27.0
3      R.J. Hunter  22.0
4    Jonas Jerebko  29.0
..             ...   ...
453   Shelvin Mack  26.0
454      Raul Neto  24.0
455   Tibor Pleiss  26.0
456    Jeff Withey  26.0
457            NaN   NaN

[458 rows x 2 columns]

In [17]:
# Adding Columns :- New columns can be added by assigning a list or series to a column name.
df['Experience'] = 1
print(df.head())

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary  Experience
0              Texas  7730337.0           1
1          Marquette  6796117.0           1
2  Boston University        NaN           1
3      Georgia State  1148640.0           1
4                NaN  5000000.0           1

In [18]:
# Deleting Columns :- You can delete a column from the DataFrame using the drop() method.
df.drop('Experience', axis=1, inplace=True)
print(df.head())

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

#### Dealing with Rows

In [19]:
# Selecting Rows :- Rows can be selected using .loc[] by row label or index.
data = pd.read_csv("nba.csv", index_col="Name")

first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]

print(first, "\n\n", second)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

 Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

In [20]:
# Adding Rows:- New rows can be added using pd.concat().
new_row = {
    'Name': 'Geeks',
    'Team': 'Boston',
    'Number': 3,
    'Position': 'PG',
    'Age': 33,
    'Height': '6-2',
    'Weight': 189,
    'College': 'MIT',
    'Salary': 99999
}
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
df.tail(2)

      Name    Team  Number Position   Age Height  Weight College   Salary
457    NaN     NaN     NaN      NaN   NaN    NaN     NaN     NaN      NaN
458  Geeks  Boston     3.0       PG  33.0    6-2   189.0     MIT  99999.0

In [21]:
# Deleting Rows :- Rows can be removed using drop() with row labels.
data = pd.read_csv("nba.csv", index_col="Name")
data.drop(["Avery Bradley", "John Holland", "R.J. Hunter"], inplace=True)

## Boolean Indexing in Pandas

In boolean indexing, we will select subsets of data based on the actual values of the data in the DataFrame and not on their row/column labels or integer locations. In boolean indexing, we use a boolean vector to filter the data.
Boolean indexing is a type of indexing that uses actual values of the data in the DataFrame.

**In boolean indexing, we can filter a data in four ways:**

- Accessing a DataFrame with a boolean index
- Applying a boolean mask to a dataframe
- Masking data based on column value
- Masking data based on an index value

In [22]:
# Accessing a DataFrame with a boolean index
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict, index = [True, False, True, False])

print(df)

         name  degree  score
True   aparna     MBA     90
False  pankaj     BCA     40
True   sudhir  M.Tech     80
False   Geeku     MBA     98

In [23]:
# Accessing a Dataframe with a boolean index using .loc[]
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict, index = [True, False, True, False])

print(df.loc[True])

        name  degree  score
True  aparna     MBA     90
True  sudhir  M.Tech     80

In [24]:
# Accessing a Dataframe with a boolean index using .iloc[]
# In order to access a dataframe using .iloc[], we have to pass a boolean value (True or False)
# but iloc[] function accepts only integer as an argument so it will throw an error so we can only access a dataframe when we pass an integer in iloc[] function.
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict, index = [True, False, True, False])

print(df.iloc[1])

name      pankaj
degree       BCA
score         40
Name: False, dtype: object

In [27]:
# Applying a boolean mask to a dataframe :
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict, index = [0, 1, 2, 3])



print(df[[True, False, True, False]])

     name  degree  score
0  aparna     MBA     90
2  sudhir  M.Tech     80

In [28]:
# Masking data based on column value:
# In a dataframe we can filter a data based on a column value.  In order to filter data, we can apply certain conditions on the dataframe using different operators like ==, >, <, <=, >=.
# When we apply these operators to the dataframe then it produces a Series of True and False.

dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["BCA", "BCA", "M.Tech", "BCA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict)

print(df['degree'] == 'BCA')

0     True
1     True
2    False
3     True
Name: degree, dtype: bool

In [29]:
data = pd.read_csv("nba.csv", index_col ="Name")
print(data['Age'] > 25)

Name
Avery Bradley    False
Jae Crowder      False
John Holland      True
R.J. Hunter      False
Jonas Jerebko     True
                 ...
Shelvin Mack      True
Raul Neto        False
Tibor Pleiss      True
Jeff Withey       True
NaN              False
Name: Age, Length: 458, dtype: bool

In [30]:
# Masking data based on index value :
# In a dataframe we can filter a data based on a column value. In order to filter data,
# we can create a mask based on the index values using different operators like ==, >, <, etc...
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["BCA", "BCA", "M.Tech", "BCA"],
        'score':[90, 40, 80, 98]}


df = pd.DataFrame(dict, index = [0, 1, 2, 3])

mask = df.index == 0

print(df[mask])

     name degree  score
0  aparna    BCA     90

In [31]:
data = pd.read_csv("nba.csv")

df = pd.DataFrame(data, index = [0, 1, 2, 3, 4, 5, 6,
                                 7, 8, 9, 10, 11, 12])

mask = df.index > 7

print(df[mask])

               Name            Team  Number Position   Age Height  Weight  \
8      Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0
9      Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0
10  Jared Sullinger  Boston Celtics     7.0        C  24.0    6-9   260.0
11    Isaiah Thomas  Boston Celtics     4.0       PG  27.0    5-9   185.0
12      Evan Turner  Boston Celtics    11.0       SG  27.0    6-7   220.0

           College     Salary
8       Louisville  1824360.0
9   Oklahoma State  3431040.0
10      Ohio State  2569260.0
11      Washington  6912869.0
12      Ohio State  3425510.0

##  Pandas Series.str.slice()
The Series.str.slice() method in pandas is used to extract substrings from each string in a Series. It works exactly like Python's standard string slicing, but applies it element-wise across the entire column.

**Syntax**

`Series.str.slice(start=None, stop=None, step=None)`

- start: Integer indicating where to begin the slice (inclusive).

- stop: Integer indicating where to end the slice (exclusive).

- step: Integer indicating the step size of the slice.

In [32]:
s = pd.Series(["apple", "banana", "cherry", "date"])

# 1. Slice from index 1 to 4
print(s.str.slice(start=1, stop=4))

# 2. Slice from the beginning to index 3 (exclusive)
print(s.str.slice(stop=3))

# 3. Slice using negative indexing (last 3 characters)
print(s.str.slice(start=-3))

# 4. Slice with a step (every 2nd character)
print(s.str.slice(step=2))

0    ppl
1    ana
2    her
3    ate
dtype: object
0    app
1    ban
2    che
3    dat
dtype: object
0    ple
1    ana
2    rry
3    ate
dtype: object
0    ape
1    bnn
2    cer
3     dt
dtype: object

**The Shorthand Alternative**

While .str.slice() is the explicit method, you can achieve the exact same results using standard Python bracket notation via the .str accessor. This is the most common way developers write it in practice:

In [33]:
s.str[1:4]   # Equivalent to s.str.slice(start=1, stop=4)
s.str[:3]    # Equivalent to s.str.slice(stop=3)
s.str[-3:]   # Equivalent to s.str.slice(start=-3)
s.str[::2]   # Equivalent to s.str.slice(step=2)

0    ape
1    bnn
2    cer
3     dt
dtype: object

## Reindexing

An important method on pandas objects is reindex, which means to create a new object with the values rearranged to align with the new index.

In [34]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Calling reindex on this Series rearranges the data according to the new index, introducing missing values if any index values were not already present:

In [35]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

For ordered data like time series, you may want to do some interpolation or filling of values when reindexing. The method option allows us to do this, using a method such as ffill, which forward-fills the values:

In [36]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [39]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

With DataFrame, reindex can alter the (row) index, columns, or both. When passed only a sequence, it reindexes the rows in the result:

In [40]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                        index=["a", "c", "d"],
                        columns=["Ohio", "Texas", "California"])

frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [41]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [42]:
# The columns can be reindexed with the columns keyword:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Because "Ohio" was not in states, the data for that column is dropped from the result.

Another way to reindex a particular axis is to pass the new axis labels as a positional argument and then specify the axis to reindex with the axis keyword:

In [43]:
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### reindex function arguments

| Argument | Description |
| :--- | :--- |
| `labels` | New sequence to use as an index. Can be Index instance or any other sequence-like Python data structure. An Index will be used exactly as is without any copying. |
| `index` | Use the passed sequence as the new index labels. |
| `columns` | Use the passed sequence as the new column labels. |
| `axis` | The axis to reindex, whether `"index"` (rows) or `"columns"`. The default is `"index"`. You can alternately do `reindex(index=new_labels)` or `reindex(columns=new_labels)`. |
| `method` | Interpolation (fill) method; `"ffill"` fills forward, while `"bfill"` fills backward. |
| `fill_value` | Substitute value to use when introducing missing data by reindexing. Use `fill_value="missing"` (the default behavior) when you want absent labels to have null values in the result. |
| `limit` | When forward filling or backfilling, the maximum size gap (in number of elements) to fill. |
| `tolerance` | When forward filling or backfilling, the maximum size gap (in absolute numeric distance) to fill for inexact matches. |
| `level` | Match simple Index on level of MultiIndex; otherwise select subset of. |
| `copy` | If `True`, always copy underlying data even if the new index is equivalent to the old index; if `False`, do not copy the data when the indexes are equivalent. |

## Dropping Entries from an Axis

Dropping one or more entries from an axis is simple if you already have an index array or list without those entries, since you can use the reindex method or .loc-based indexing. As that can require a bit of munging and set logic, the drop method will return a new object with the indicated value or values deleted from an axis:

In [44]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [45]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [46]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [48]:
# With DataFrame, index values can be deleted from either axis.
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                       index=["Ohio", "Colorado", "Utah", "New York"],
                      columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [49]:
# Calling drop with a sequence of labels will drop values from the row labels (axis 0):
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [50]:
# To drop labels from the columns, instead use the columns keyword:
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [51]:
# You can also drop values from the columns by passing axis=1 (which is like NumPy) or axis="columns":
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [52]:
data.drop(["two", "four"], axis="columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14