<a href="https://colab.research.google.com/github/sandeep838116/Pandas/blob/main/Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas is a newer package built on the top of NumPy, and provides an efficient implementation of a DataFrame. DataFrames are essentially multidimensional arrays with attached row and column labels, and often with heterogenous types and/or missing data. As well ass offering a convenient storage interface for labeled data.

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

# Introducing Pandas Objects
- At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integers.

In [2]:
import numpy as np
import pandas as pd

## The Pandas Series Object

In [4]:
# A Pandas series is one-dimensional array of indexed data.
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
# The Series wraps both a sequence of values and a sequence of indices, which we can access with the values and index attributes.
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
# The index is an array-like object of type pd.Index
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
#Like with a NumPy array, data can be accessed by the associated index via the fimiliar Python square-bracket notation:
data[1]

np.float64(0.5)

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### Series as generalized NumPy array
- From what we have seen so far, it may look the Series object is basically interchangeable with one-dimensional NumPy array.
- The essential difference is the presence of index: While the NumPy array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.
- This explicit index definition gives the Series object additional capablities.For example, the index need not be an integer, but can consist of values of any desired type.

In [9]:
data=pd.Series([0.25,0.2,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.20
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

np.float64(0.2)

In [11]:
# We can even use noncontigous or nonsequential indices:
data=pd.Series([0.25,0.2,0.75,1.0],index=[2,5,3,7])
data

2    0.25
5    0.20
3    0.75
7    1.00
dtype: float64

In [12]:
data[5]

np.float64(0.2)

### Series as specialized dictionary
- A dictionary is a structure that maps types keys to a set of arbitary values, and a Series is structure that maps typed keys to a set of typed values.
- This typing is important: just as the type-specific compiled code behind a NumPy array make it more efficient than a Python list for certain operations, the type information of a Pandas Series makes it more efficient than Python dictionaries for certain operations.

In [14]:
# We can make the Series-as-dictionary analogy even more clear by constructing a series object directly from a Python dictionary:
population_dict={'California':123456789,
                 'Sasaram':789456123,
                 'Delhi':741852963,
                 'Kolkata':963852741,
                 'Varanasi':159263487}
population = pd.Series(population_dict)
population

California    123456789
Sasaram       789456123
Delhi         741852963
Kolkata       963852741
Varanasi      159263487
dtype: int64

In [15]:
population['Sasaram']

np.int64(789456123)

In [16]:
# Unlike a dictionary, though, the series also supports array-style operations such as slicing
population['California':'Kolkata']

California    123456789
Sasaram       789456123
Delhi         741852963
Kolkata       963852741
dtype: int64

### Constructing series objects

In [18]:
pd.Series(data)

2    0.25
5    0.20
3    0.75
7    1.00
dtype: float64

In [19]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [20]:
# data can be scalar, which is represented to fill the specified index:
pd.Series(5,index=[1,2,3,4,5,6])

1    5
2    5
3    5
4    5
5    5
6    5
dtype: int64

In [21]:
#data can be a dictionary, in which index defaults to the sorted dictionary keys
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [22]:
# In each case, index can be explicitly set if a different result is prefered
pd.Series({2:'a',1:'b',3:'c'},index=[3,2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

### DataFrame as a generalized NumPy array
- If a series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names.
- Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a DataFrame as a sequence of aligned Series objects. Here, aligned means they share the same index.

In [23]:
area_dict={'California':123456,
                 'Sasaram':789456,
                 'Delhi':741852,
                 'Kolkata':963852,
                 'Varanasi':159263}
area = pd.Series(area_dict)
area

California    123456
Sasaram       789456
Delhi         741852
Kolkata       963852
Varanasi      159263
dtype: int64

In [26]:
# Now that we have this along with the population Series from before, we can use a dictionary to construct a single two-dimensional object
states=pd.DataFrame({'population':population,
                     'area':area})
states

            population    area
California   123456789  123456
Sasaram      789456123  789456
Delhi        741852963  741852
Kolkata      963852741  963852
Varanasi     159263487  159263

In [27]:
#Like series object, the DataFrame has an index attribute that gives access to the index labels:
states.index

Index(['California', 'Sasaram', 'Delhi', 'Kolkata', 'Varanasi'], dtype='object')

In [29]:
# Additionally, the DataFrame has a column attribute, which is an Index object holding the column labels:
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as specialized dictionary
- Similarly, we can think of a DataFrame as a specialization of a dictionary. Where a dictionary maps a keys to a value, a DataFrame maps a column name to a Series of column data.

In [30]:
states['area']

California    123456
Sasaram       789456
Delhi         741852
Kolkata       963852
Varanasi      159263
Name: area, dtype: int64

Notice the potential point of confusion here: in a two-dimensional NumPy array, data[0] will return the first row. For a DataFrame, data['col0'] will return the first column. Because of this, it is probably better to think about Dataframes as generalized dictionaries rather than generalized arrays.

### Constructing DataFrame objects

In [31]:
# From a single Series Object
# A DataFrame is a collection of Series objects, and a single-column DataFrame can be constructed from a single Series.
pd.DataFrame(population,columns=['population'])

            population
California   123456789
Sasaram      789456123
Delhi        741852963
Kolkata      963852741
Varanasi     159263487

In [33]:
# From a list of dicts
# Any list of dictionaries can be made into a DataFrame.
data =[{'a':i,'b':2*i} for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

In [34]:
# Even if some keys in the dictionary are missing, Pandas will fill them in with NaN(i.e.,"not a number") values
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [35]:
# From a dictionary of Series objects
pd.DataFrame({'population':population,'area':area})

            population    area
California   123456789  123456
Sasaram      789456123  789456
Delhi        741852963  741852
Kolkata      963852741  963852
Varanasi     159263487  159263

In [36]:
# From a two-dimensional NumPy array
pd.DataFrame(np.random.rand(3,2),
             columns=['foo','bar'],
             index=['a','b','c'])

        foo       bar
a  0.036298  0.719144
b  0.997058  0.800736
c  0.149808  0.071248

In [38]:
# From NumPy structured array
A = np.zeros(3,dtype=[("A",'i8'),('B','f8')])
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object
- The Index object is an intresting structure in itself, and it can be thought of either as an immutable array or as an order set (technically a multiset, as Index objects may contain repeated values). Those views have some intresting consequences in the operations available on Index objects.

In [40]:
ind = pd.Index([2,3,4,5,7])
ind

Index([2, 3, 4, 5, 7], dtype='int64')

### Index as immutable array

In [41]:
ind[1]

np.int64(3)

In [42]:
ind[::2]

Index([2, 4, 7], dtype='int64')

In [43]:
# One difference difference between Index objects and NumPy arrays is that indices are immutable-that is, they cannot be modified via the normal means.
ind[1]=0

TypeError: Index does not support mutable operations

This immutability makes it safer to share indices between multiple DataFrames and arrays, without the potential for side effects from inadvertent index modifications.

### Index as ordered set
- Pandas objects are designed to facilitate operations such as join across datasets, which depend on many aspects of set arithemetic. The index object follows many of the conventions used by Python's built-in set data structure, so that unions, intersections, difference, and other combinations can be computed in a fimilar way.

In [44]:
indA=pd.Index([1,3,5,7,9])
indB=pd.Index([2,3,5,7,11])

In [45]:
indA&indB

Index([0, 3, 5, 7, 9], dtype='int64')

In [47]:
indA | indB

Index([3, 3, 5, 7, 11], dtype='int64')

In [48]:
indA ^ indB

Index([3, 0, 0, 0, 2], dtype='int64')